version: '3.8'
services:
  web:
    build: .
    container_name: aduser-registry
    ports:
      - "8080:80"
    volumes:
      - ./src:/app/src
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8080

volumes:
  node_modules: